# Generated by Django 4.1.1 on 2022-10-15 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='Bot',
            new_name='bot',
        ),
        migrations.RenameField(
            model_name='conversations',
            old_name='Bot',
            new_name='bot',
        ),
    ]
